package com.momo.toys.be.enumeration;

public enum SupportedType{

    ACCOUNT_CREATION,
    ACCOUNT_UPDATING,
    NAVIGATION_CREATION,
    DOCUMENT_UPLOADING,
    PRODUCT_CREATION,
    REVIEW_CREATION,
    ORDER_CREATION,
    ORDER_VERIFY_AMOUNT
}
